#cloud-config
users:
  - name: opam
    groups: [sudo]
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA09mqKPpMJ4tyOpl4l+KTTl1DqjFT2mRD29HW8VwnmB root@alpha
runcmd:
  - echo "AcceptEnv=*" > /etc/ssh/sshd_config.d/acceptenv.conf
  - apt update
  - apt upgrade -y
  - poweroff
